spring:
  application:
    name: starforge-mcp
  main:
    banner-mode: "off"
    web-application-type: none
  profiles:
    include: qdrant

# PDF Processing Configuration
pdf:
  chunking:
    size: 1000
    overlap: 100

# Logging
logging:
  level:
    com.spyder: INFO
    root: WARN